### ISSUE TITLE
OnClient error not called after Connection

### ISSUE THREAD

**Issue by DonatienGascoin** [MirrorNetworking/SimpleWebTransport#24]
I was trying to show a message "Impossible to access the server" when the server was not running, and I was not able to get an OnClientError trigger. I've solved my problem this way :

Step to reproduce:
- Add a SimpleWebTransport as you main transport
- Try to connect to a server not running

You will be disconnected well, but the "OnClientError" event will not be triggered.

That's working if you invert the 2 lines in SimpleWebTransport
```
client.onError += (Exception e) =>
            {
                ClientDisconnect();
                OnClientError.Invoke(e);
            };
```

Become 
```
client.onError += (Exception e) =>
            {
                OnClientError.Invoke(e);
                ClientDisconnect();
            };
```

**Comment by James-Frowen** [comment]
Nice find, I've committed the fix

**Comment by DonatienGascoin** [comment]
Hi James, FYI, I have not created a PR myself because I did not have the time to test if it was working with a WebSocketClientWebGl, I have only tested it with WebSocketClientStandalone. 
As the fix is on SimpleWebTransport, I exept this to work, but some test can't harm :)

Cheers
